export * from './header';
export * from './footer';
export * from './hero';
export * from './temp-mail/main';
export * from './blog';
export * from './blog-detail';
export * from './pricing';
export * from './faq';
export * from './testimonials';
